version: '3.8'

services:
  springboot-app:
    build: .
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
